#!/bin/bash

# Ensure the eval script exists and can be sourced
if [ ! -f Linoop-eval-script ]; then
    echo "Error: Linoop-eval-script file not found!"
    exit 1
fi

if ! source Linoop-eval-script 2>/dev/null; then
    echo "Error: Cannot source Linoop-eval-script"
    exit 1
fi

while true; do
    read -p "Please select question (all or 1-25 or q to quit): " question
    question=$(echo "$question" | tr '[:upper:]' '[:lower:]')
    echo ""

    case "$question" in
        1) check_pw ;;
        2) check_IP ;;
        3) check_repos ;;
        4) check_chrony ;;
        5) check_autofs ;;
        6)
            check_grp
            check_users
            check_grp_membership
            check_usr_shell
            check_sudo
            check_umask
            ;;
        7)
            check_enforce_pw
            check_acc_exp
            ;;
        8) check_max_days ;;
        9)
            check_setgid_perm
            check_sticky_bit
            ;;
        10) check_grp_pkg ;;
        11) check_selinux ;;
        12) check_bzip2_compression ;;
        13) check_journal ;;
        14) check_tuned_profile ;;
        15) 
            check_cron 
            check_natasha_cron_block
            ;;
        16) check_lvm1 ;;
        17) check_lvm2 ;;
        18) check_lvm3 ;;
        19) check_swap ;; 
        20) 
            check_ACL 
            check_ACL_bob  
            ;;
        21) 
            check_webimage 
            check_web_container1
            check_pdf_file_conversion
            ;; 
        22) 
            check_new_webimage 
            check_container_myweb1
            check_pdf_file_conversion
            ;; 
        23) check_autofs_config ;; 
        24) check_find_tasks ;;
        25) check_grep_tasks ;;

        all)
            check_pw
            check_IP
            check_repos
            check_chrony
            check_autofs
            check_grp
            check_users
            check_grp_membership
            check_usr_shell
            check_sudo
            check_umask
            check_enforce_pw
            check_acc_exp
            check_max_days
            check_setgid_perm
            check_sticky_bit
            check_grp_pkg
            check_selinux
            check_bzip2_compression
            check_journal
            check_tuned_profile
            check_cron
            check_natasha_cron_block
            check_lvm1
            check_lvm2
            check_lvm3
            check_swap
            check_ACL 
            check_ACL_bob  
            check_webimage 
            check_web_container1
            check_pdf_file_conversion
            check_new_webimage 
            check_container_myweb1
            check_pdf_file_conversion
            check_autofs_config
            check_find_tasks
            check_grep_tasks
            ;;
        q) break ;;
        *) echo "You did not select a valid question number." ;;
    esac
done
