#!/bin/bash

if ! source Linoop-eval-script 2>/dev/null; then
    echo "Error: Cannot source Linoop-eval-script"
    exit 1
fi

while true; do
    read -p "Please select question (all or 1-16 or q to quit): " question
    question=$(echo "$question" | tr '[:upper:]' '[:lower:]')
    echo ""

    case "$question" in
        1) check_pw ;;
        2) check_IP ;;
        3) check_repos ;;
        4) check_chrony ;;
        5) validate_autofs ;;
        6)
            check_grp
            check_users
            check_grp_membership
            check_usr_shell
            chk_sudo
            check_umask
            ;;
        7)
            chk_enforce_pw
            chk_acc_exp
            ;;
        8) chk_max_days ;;
        9)
            check_setgid_perm
            check_sticky_bit
            ;;
        10) chk_grp_pkg ;;
        11) check_selinux ;;
        12) check_bzip2_compression ;;
        13) check_journal ;;
        14) check_tuned_profile ;;
        15) check_cron ;;
        16) check_natasha_cron_block ;;
        17) check_lvm1 ;;
        18) check_lvm2 ;;
        19) check_lvm3 ;;
        20) swap_check ;; 
        all)
            check_pw
            check_IP
            check_repos
            check_chrony
            validate_autofs
            check_grp
            check_users
            check_grp_membership
            check_usr_shell
            chk_sudo
            check_umask
            chk_enforce_pw
            chk_acc_exp
            chk_max_days
            check_setgid_perm
            check_sticky_bit
            chk_grp_pkg
            check_selinux
            check_bzip2_compression
            check_journal
            check_tuned_profile
            check_cron
            check_natasha_cron_block
            check_lvm1
            check_lvm2
            check_lvm3
            swap_check
            ;;
        q) break ;;
        *) echo "You did not select a valid question number." ;;
    esac
done
