#!/bin/bash

if [ `id -u` != 0 ];then
        echo ""
        echo -e "\e[31m Failed: Please Run this Script as root\e[0m\n"
        exit 1
fi

echo "RUNNING TASK 1 ......................."
dnf install httpd -y -q &>/dev/null

echo "RUNNING TASK 2 ......................."
systemctl enable httpd --now &>/dev/null

echo "RUNNING TASK 3 ......................."
firewall-cmd --add-service={http,https} --permanent &>/dev/null
firewall-cmd --add-port={80/tcp,443/tcp} --permanent &>/dev/null
firewall-cmd --reload &>/dev/null

echo "RUNNING TASK 4 ......................."
cd /var/www/html
git clone https://github.com/saim-ali-hub/saim_repo.git

echo "RUNNING TASK 5 ......................."
mkdir /remoteusers

echo "RUNNING TASK 6 ......................."
# Define an array of usernames and their corresponding UIDs
declare -A users
users=( ["user1"]=4001 ["user2"]=4002 ["user3"]=4003 )

# Loop through the array and create users with specific UIDs
for user in "${!users[@]}"; do
    uid=${users[$user]}
    sudo useradd -u $uid -b /remoteusers $user >/dev/null
    if [ $? -eq 0 ]; then
        echo "User $user with UID $uid created successfully."
    else
        echo "Failed to create user $user with UID $uid."
    fi
done

echo "RUNNING TASK 7 ......................."
echo "/remoteusers *(rw,sync)" > /etc/exports
exportfs -avr  &>/dev/null
firewall-cmd --add-service={ntp,mountd,rpc-bind} --permanent &>/dev/null
firewall-cmd --reload &>/dev/null
systemctl enable nfs-server --now
